### ISSUE TITLE
Encapsulate SCSS-generated CSS with each component

### ISSUE THREAD

**Issue by maxatdetroit** [CityOfDetroit/COD-Design-System#115]
**Is your feature request related to a problem? Please describe.**

See https://github.com/CityOfDetroit/COD-Design-System/pull/112#issuecomment-1810363230.

**Describe the solution you'd like**

The build script `compile-bootstrap.sh` should be renamed to `compile-styles.sh` and there should be a section in the script for each component with SCSS code to compile. The script should generate a separate CSS per component.

**Describe alternatives you've considered**

See https://github.com/CityOfDetroit/COD-Design-System/pull/112#issuecomment-1810363230 where we currently store all SCSS-generated CSS into a single `themed-bootstrap.css` file.

**Comment by maxatdetroit** [comment]
## What's the problem here?

In a few PRs - [PR 112](https://github.com/CityOfDetroit/COD-Design-System/pull/112/files) and [PR 128](https://github.com/CityOfDetroit/COD-Design-System/pull/128/files) - we started adding CSS for specific components to our customized bootstrap CSS. See the SCSS for those components imported here: https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/scss/themed-bootstrap.scss#L108-L115.

The SCSS in [`themed-bootstrap.scss`](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/scss/themed-bootstrap.scss) gets compiled into CSS ([`themed-bootstrap.css`](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/shared/themed-bootstrap.css)) by a Bash script called [`compile-bootstrap.sh`](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/scripts/compile_bootstrap.sh). That CSS ([`themed-bootstrap.css`](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/shared/themed-bootstrap.css)) then gets included in every single component in the design system (e.g. imported in [Alert.js](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/components/atoms/Alert/Alert.js#L3)).

Which leads us to the problem: when we include CSS for specific components into our themed bootstrap CSS, we're including CSS that not all components need but then importing that CSS into all components. This increases the file size for each components and also makes it possible to accidentally introduce conflicting styles if different components use similar CSS selectors.

## What's the solution?

Separate out the component-specific CSS into self-contained CSS files for each component. Specifically that'll require doing the following:

1. Rename `compile-bootstrap.sh` to `compile-styles.sh`
2. Add a function in `compile-styles.sh` to compile SCSS for each component that has custom SCSS (see each component here: https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/scss/themed-bootstrap.scss#L108-L115). The output CSS should be placed in the relevant component directory.
3. Remove those component SCSS imports from `themed-bootstrap.scss` ([here](https://github.com/CityOfDetroit/COD-Design-System/blob/dev/src/scss/themed-bootstrap.scss#L108-L115)).
5. Update each component's Javscript to include the generated CSS for that component (e.g. [like this](https://github.com/CityOfDetroit/COD-Design-System/blob/6a880918ff718f678cfd34798672a37fcb8dab67/src/components/organisms/Table/Table.js#L1C1-L1C47)).

## Resources

1. If you're not familiar with Bash: https://linuxconfig.org/bash-scripting-tutorial-for-beginners
2. If you're not familiar with SASS/SCSS: https://sass-lang.com/guide/
  * Note: SASS is already setup in the project. To compile CSS from SCSS you simply need to execute `yarn sass <input-file>.scss <output-file>.css`. See the example in the current compilation script [here](https://github.com/CityOfDetroit/COD-Design-System/blob/6a880918ff718f678cfd34798672a37fcb8dab67/scripts/compile_bootstrap.sh#L14).

**Comment by KaeTheDev** [comment]
Okay so for the components, its all of these that need their own section @maxatdetroit:                                             

- table-header
- table-row
- table-cell-header
- table-cell
- nav
- off canvas
- offcanvasheader
- offcanvasbody

**Comment by maxatdetroit** [comment]
Yep, that's right. There will need to be a CSS file generated for each of those components.

**Comment by KaeTheDev** [comment]
### BREAK DOWN OF TASK TO COMPLETE SOLUTION:

- [ ] TASK 1: Set up the design system locally -> set it up locally using https://github.com/CityOfDetroit/COD-Design-System#contributing

- [ ] TASK 2: Re-name the file compile-bootstrap.sh to compile-styles.sh in the design system directory after setting it locally

- [ ] TASK 3: Add a function in the compile-styles.sh to compile SCSS for each component that has custom SCSS. Components ->

- [ ]  table-header
- [ ]  table-row
- [ ] table-cell-header
- [ ]  table-cell
- [ ]  nav
- [ ] off canvas
- [ ]  offcanvasheader
- [ ]  offcanvasbody

**MORE NOTES ON TASK 3:** Each component should have its own CSS file. The output CSS should be placed in the relevant component directory.

- [ ] TASK 4: Remove the component SCSS imports from themed-bootstrap.scss. The section looks like this: 
// _____  _   _  _____  _____  _____ ___  ___
// /  __ \| | | |/  ___||_   _||  _  ||  \/  |
// | /  \/| | | |\ `--.   | |  | | | || .  . |
// | |    | | | | `--. \  | |  | | | || |\/| |
// | \__/\| |_| |/\__/ /  | |  \ \_/ /| |  | |
//  \____/ \___/ \____/   \_/   \___/ \_|  |_/
//  _____  _____ __   __ _      _____  _____
// /  ___||_   _|\ \ / /| |    |  ___|/  ___|
// \ `--.   | |   \ V / | |    | |__  \ `--.
//  `--. \  | |    \ /  | |    |  __|  `--. \
// /\__/ /  | |    | |  | |____| |___ /\__/ /
// \____/   \_/    \_/  \_____/\____/ \____/
//
// This section contains component specific SASS styles.
@import '../components/atoms/TableHeader/table-header';
@import '../components/atoms/TableRow/table-row';
@import '../components/atoms/TableCellHeader/table-cell-header';
@import '../components/atoms/TableCell/table-cell';
@import '../components/molecules/Nav/nav';
@import '../components/organisms/Offcanvas/offcanvas';
@import '../components/atoms/OffcanvasHeader/offcanvasheader';
@import '../components/atoms/OffcanvasBody/offcanvasbody';

- [ ] TASK 5: Update each component's Javscript to include the generated CSS for that component (e.g. [like this](https://github.com/CityOfDetroit/COD-Design-System/blob/6a880918ff718f678cfd34798672a37fcb8dab67/src/components/organisms/Table/Table.js#L1C1-L1C47)).

**Comment by KaeTheDev** [comment]
Okay, when you say "The output CSS should be placed in the relevant component directory." what do you mean? Is that related to creating a separate CSS file for each component @maxatdetroit?

**Comment by sreidthomas** [comment]
### BREAK DOWN OF TASKS TO COMPLETE SOLUTION:

- [x] TASK 1: Set up the design system locally -> set it up locally using https://github.com/CityOfDetroit/COD-Design-System#contributing

- [x] TASK 2: Re-name the file **compile-bootstrap.sh** to **compile-styles.sh** in the design system directory after setting it up locally -> file name is **compile_bootstrap.sh** so should be renamed to **compile_styles.sh**

- [ ] TASK 3: Add a function in the **compile-styles.sh** to compile SCSS for each component that has custom SCSS. Components ->


**CHECK EACH COMPONENT OFF AS ITS COMPLETED:**
- [ ]  table-header
- [ ]  table-row
- [ ] table-cell-header
- [ ]  table-cell
- [ ]  nav
- [ ] off canvas
- [ ]  offcanvasheader
- [ ]  offcanvasbody

**MORE NOTES ON TASK 3:** Each component should have its own CSS file. The output CSS should be placed in the relevant component directory.

- [x] TASK 4: Remove the component SCSS imports from themed-bootstrap.scss. The section looks like this: 
// _____  _   _  _____  _____  _____ ___  ___
// /  __ \| | | |/  ___||_   _||  _  ||  \/  |
// | /  \/| | | |\ `--.   | |  | | | || .  . |
// | |    | | | | `--. \  | |  | | | || |\/| |
// | \__/\| |_| |/\__/ /  | |  \ \_/ /| |  | |
//  \____/ \___/ \____/   \_/   \___/ \_|  |_/
//  _____  _____ __   __ _      _____  _____
// /  ___||_   _|\ \ / /| |    |  ___|/  ___|
// \ `--.   | |   \ V / | |    | |__  \ `--.
//  `--. \  | |    \ /  | |    |  __|  `--. \
// /\__/ /  | |    | |  | |____| |___ /\__/ /
// \____/   \_/    \_/  \_____/\____/ \____/
//
// This section contains component specific SASS styles.
@import '../components/atoms/TableHeader/table-header';
@import '../components/atoms/TableRow/table-row';
@import '../components/atoms/TableCellHeader/table-cell-header';
@import '../components/atoms/TableCell/table-cell';
@import '../components/molecules/Nav/nav';
@import '../components/organisms/Offcanvas/offcanvas';
@import '../components/atoms/OffcanvasHeader/offcanvasheader';
@import '../components/atoms/OffcanvasBody/offcanvasbody';

- [x] TASK 5: Update each component's Javscript to include the generated CSS for that component (e.g. [like this](https://github.com/CityOfDetroit/COD-Design-System/blob/6a880918ff718f678cfd34798672a37fcb8dab67/src/components/organisms/Table/Table.js#L1C1-L1C47)).


### **CREATED PR FOR THE ISSUE:**
https://github.com/CityOfDetroit/COD-Design-System/pull/136

**Comment by sreidthomas** [comment]
Okay, when you say "The output CSS should be placed in the relevant component directory." what do you mean? Is that related to creating a separate CSS file for each component @maxatdetroit?

**Comment by sreidthomas** [comment]
When setting up the Design System locally, step 2 just says "Yarn". That's supposed to be Yarn Install right? @maxatdetroit -> correction just tried yarn install and it did not work. Neither did just yarn

<img width="722" alt="Screenshot 2024-01-04 at 1 45 13 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/91641738-2994-4e51-8fc8-743f765560ce">

**Comment by maxatdetroit** [comment]
> it did not work. Neither did just yarn

@sreidthomas , this doesn't give me much to go on. Would you tell me more about what happened? Example output would be helpful. Feel free to send it over chat since setup isn't related to this issue/task.

**Comment by sreidthomas** [comment]
I cloned the project. I did yarn and it said command not found. I did yarn install and got the same thing:
<img width="569" alt="Screenshot 2024-01-04 at 1 59 01 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/2c1d893c-c04b-4d65-ba30-53c4f0ea1c6a">

**Comment by sreidthomas** [comment]
Unless that means I don't have yarn installed on my system. Should I do "npm install yarn" globally? @maxatdetroit

**Comment by maxatdetroit** [comment]
That's exactly what that means 👌

Yes, run `npm install --global yarn`. If your system can't find the `npm` command, you'll have to install node first. Let me know if that happens and I can recommend how to install node.

**Comment by sreidthomas** [comment]
I know I have to create a new branch but it's showing 177 commits. I can just ignore that right @maxatdetroit 

<img width="337" alt="Screenshot 2024-01-04 at 2 15 52 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/0a5afe31-63ec-4346-b8a3-ad8bc479e8a7">

This is after **git status**:
<img width="574" alt="Screenshot 2024-01-04 at 2 16 47 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/662f03ff-5e68-40f1-b3d2-5921311a5121">

**Comment by maxatdetroit** [comment]
Those are generated files probably from running `yarn build-storybook`. You can actually delete that folder: `rm -r storybook-static`. You don't need to run `yarn build-storybook` during development. Just `yarn storybook`.

**Comment by sreidthomas** [comment]
Oh okay. I did just run that too. Wasn't sure. Just following the directions under set up. got it, thanks

**Comment by maxatdetroit** [comment]
Yea the readme should be more clear about which command is needed in which scenario. If you have a second, go ahead and create a PR adding a note above that command in the `readme.md` that says:

You only need to run `yarn build-storybook` if you're creating a new production release of the design system. For development, all that's needed is `yarn storybook`.

**Comment by sreidthomas** [comment]
I am on task 3 and it says create a function to compile SCSS. There's a function compile_sass do I need to edit that one or do I need another function: compile_scss:

<img width="1017" alt="Screenshot 2024-01-04 at 3 09 58 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/5a2c71d1-d413-4c33-9307-7110e1f1d58d">



And it says that each component needs its own CSS file. Inside src > components > atoms > table-header (for example) there's already a CSS file and for the rest of the components too:

<img width="242" alt="Screenshot 2024-01-04 at 3 10 11 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/a47ea5ee-e830-42fd-9926-36fa9d3f6dfa">

**Comment by maxatdetroit** [comment]
Both of those are good observations.

For the function: I recommend renaming `compile_sass` to be called `compile_bootstrap`, then creating a new function named `compile_components` that handles compiling each components SCSS to CSS.

For the preexisting CSS files in each components folder: you can move all the CSS rules in the existing CSS file (if there are any) to the top of the similarly named SCSS file. Then, delete that existing CSS file and let it get generated by SASS and your bash script. For example, with TableHeader:
* Move the rules in `TableHeader.css` into `_table-header.scss`.
* Delete `TableHeader.css`
* In the bash script, make the output of `yarn sass` be `TableHeader.css` for the TableHeader component (like `yarn sass ${PROJECT_ROOT}src/components/atoms/_table_header.scss ${PROJECT_ROOT}src/components/atoms/TableHeader.css`)

With this approach, you also won't have to update the Javascript files for the components, since they're already importing those CSS files (like `TableHeader.css`).

**Comment by sreidthomas** [comment]
I'm still trying to figure out the actual script code. I'm just working on the pseudocode but am I overthinking it @maxatdetroit :     


The sass files can be in either the atoms, molecules or organisms folders which is inside the components directory (src > components > atoms, molecules, organisms) so using a variable:

* Variable Setup:
    * Define a variable to hold the names of folders - atoms, molecules, organisms.
    * Set the base path as ${PROJECT_ROOT}src/components/.
* Loop through Folders:
    * Iterate through each folder specified by the variable to find SASS files -> ${PROJECT_ROOT}src/components/{NAMES_OF_FOLDER}
    * identify SASS files (using =>  _*.scss).
* Conversion to CSS:
    * For each found SASS file, use yarn sass command to convert it to CSS.

**Comment by maxatdetroit** [comment]
First, I want to commend you for thinking through that proposed approach. Let's call it approach number 1. That would be "next-level". 

Alternatively, you could take a simpler approach, although it would require more work each time a new component SCSS file is added in the future. Let's call it approach number 2:

1. Variable Setup:
    * Define a variable that holds an array of component SCSS file names
2. Loop through component SCSS files:
    * For each found SASS file, use yarn sass command to convert it to CSS.

This means each time a developer wants to create a new SCSS file for a component, they would have to go into the script and add the SCSS file to the variable array.


Both approach number 1 and approach number 2 have pros/cons, and there is no right answer. In fact, I actually like your approach more than my suggestion. That being said, if you decide to go with your approach, please add one more step (third step below):


1. Variable Setup:
    * Define a variable to hold the names of folders - atoms, molecules, organisms.
    * Set the base path as ${PROJECT_ROOT}src/components/.
2. Loop through Folders:
    * Iterate through each folder specified by the variable to find SASS files -> ${PROJECT_ROOT}src/components/{NAMES_OF_FOLDER}
    * identify SASS files (using =>  _*.scss).
3. Confirm list of files with the user:
    * Print the list of files found to the command line and ask the user to confirm (e.g. input 'yes'), skip component CSS generation (e.g. input 'skip'), or abort the script (e.g. input 'abort'). This will give the developer an opportunity to prevent unintended SCSS files from being picked up by the script. For example, we shouldn't generate CSS from SCSS mixins.
4. Conversion to CSS:
    * For each found SASS file, use yarn sass command to convert it to CSS.

**Comment by sreidthomas** [comment]
I appreciate that . Thank you.. So I can try my solution. Have to re-think a little because you said we don't want to include SCSS mixins and those end in .scss too correct? Also, when you say print the list of files I'm thinking: loop through the folders, find the .scss files and store them somewhere so that later they can be printed out and checked individually? Am I understanding what you're saying? 

NOTE: Update on the mixin. I'm looking at the set up in the directory and it looks like all the mixins are in one file: _table.scss(EDIT: looks like we currently only have one file with mixins. I'm assuming this can grow over time depending on which components need mixins. Even with that, still wondering if that particular section of the directory can be ignored). So even though I'm using a wildcard to identify .scss files maybe there is a way to exclude that particular file? 

So we have scss(folder) -> mixins (folder) -> _table.scss(file). Since the wildcard includes all files with _ and it looks like all the .scss files are using that maybe with this particular function (if possible) ignore that whole scss folder. It also has: _host.scss and themed-bootstrap.scss files inside it:

<img width="271" alt="Screenshot 2024-01-05 at 1 07 55 PM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/141044304/9da47b30-77a0-4e7e-8634-306cb60c3c47">

**Comment by maxatdetroit** [comment]
> Also, when you say print the list of files I'm thinking: loop through the folders, find the .scss files and store them somewhere so that later they can be printed out and checked individually? Am I understanding what you're saying?

Yep, perfectly.

And yes, your hunch regarding mixins is right. As long as you only search for SCSS files in `src/components/{atoms|molecules|organisms}/_*.scss` you shouldn't pick up any mixins anyway. Since mixins should be stored in `src/scss/`.

There's the off chance that someone accidentally puts a mixin in `src/components/{atoms|molecules|organisms}/` which is why we're going to add the output and confirmation from the script user. To guard against that possibility.
