### ISSUE TITLE
Create Video Player component

### ISSUE THREAD

**Issue by jedgar1mx** [CityOfDetroit/COD-Design-System#220]
We need to create a video player component for the new legacy site. It should open a modal on click where the video can be played.

![Image](https://github.com/CityOfDetroit/COD-Design-System/assets/21081923/aacc7b46-e902-46ef-b902-684a4a7e37c6)

**Comment by maxatdetroit** [comment]
We'll use:

* Regular fluid-container div with black background as a placeholder until the thumbnail image loads and play button absolute positioned overlay
* Bootstrap modal component: https://getbootstrap.com/docs/5.3/components/modal/
* The YT embed video API to generate the embed iframe via Javascript: https://developers.google.com/youtube/iframe_api_reference
* Custom stylesheets to make the video iframe size responsive and respect aspect ratio:

```
.yt-video {
  width: 100%;
  aspect-ratio: 16/9;
}
```
