### ISSUE TITLE
Build Image overlay component

### ISSUE THREAD

**Issue by jedgar1mx** [CityOfDetroit/COD-Design-System#222]
We need to create a new overlay image component. It should have two states

1. Text visible: On hover - an image would show and the text would fade out. On click -it should link to a particular URL
2. Image is visible: On hover - text would show and image would fade out. On click -it should link to a particular URL

![Image](https://github.com/CityOfDetroit/COD-Design-System/assets/21081923/d9d8ad9b-658f-4d87-aa60-1f8d16c2d04b)

**Comment by maxatdetroit** [comment]
Support gif (low-pri). May not want this.
